server:
  service:
    type: ClusterIP
  ingress:
    enabled: false
    
alertmanager:
  service:
    type: ClusterIP
  ingress:
    enabled: false
    
grafana:
  service:
    type: ClusterIP
  ingress:
    enabled: false
  adminPasswordKey: admin-password
  adminPasswordSecret: grafana-admin-password
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

serviceMonitors:
  - name: backend-metrics
    namespace: default
    selector:
      matchLabels:
        app: backend
    endpoints:
      - port: http
        path: /metrics
        interval: 15s

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: <External-IP>
      paths:
        - path: /prometheus(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: prometheus-server
              port:
                number: 9090
        - path: /alertmanager(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: alertmanager
              port:
                number: 9093
        - path: /grafana(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 3000
        - path: /argocd(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 80
