server:
  service:
    type: ClusterIP  # Use ClusterIP for internal routing
alertmanager:
  service:
    type: ClusterIP
grafana:
  service:
    type: ClusterIP
grafana:
  adminPasswordKey: admin-password
  adminPasswordSecret: grafana-admin-password
serviceMonitors:
  - name: backend-metrics
    namespace: default
    selector:
      matchLabels:
        app: backend
    endpoints:
      - port: http
        path: /metrics
        interval: 15s

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: monitoring.yourdomain.com change to <External-IP>
      paths:
        - path: /prometheus
          pathType: Prefix
        - path: /alertmanager
          pathType: Prefix
        - path: /grafana
          pathType: Prefix
        - path: /argocd
          pathType: Prefix
