apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::799344209838:role/Project-Role-K8
      username: jenkins
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::799344209838:user/anshu
      username: anshu
      groups:
        - system:masters
