apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-clus
  region: us-west-2
  version: "1.32"

nodeGroups:
  - name: stand-work
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    managed: true

iam:
  withOIDC: true

awsAuth:
  additionalRoles:
    - rolearn: arn:aws:iam::799344209838:role/Project-Role-K8
      username: jenkins
      groups:
        - system:masters
  additionalUsers:
    - userarn: arn:aws:iam::799344209838:user/anshu
      username: anshu
      groups:
        - system:masters
