apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shashank9928/linkproj-be:10
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "myprimarypgdb.clushmnnhufs.us-west-2.rds.amazonaws.com"
            - name: DB_USER
              value: "shank"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DBPASS
            - name: DB_NAME
              value: "primarydb"
            - name: READ_REPLICA_HOST
              value: "myreplicapgdb.clushmnnhufs.us-west-2.rds.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30088
  type: NodePort
